Fix carrierwave backgrounder API change
NoMethodError:
  undefined method `cache_name' for #<CarrierWave::Mounter:0x00007fd725b2a198>
  Did you mean?  cache_names
                cache_names=
 ./spec/models/b_param_spec.rb:12:in `block (3 levels) in <top (required)>'

Related:
https://github.com/lardawge/carrierwave_backgrounder/issues/200