Kill CarrierWave::MimeTypes
Automatically included with update
https://github.com/carrierwaveuploader/carrierwave/issues/1887#issuecomment-202323351

NameError: uninitialized constant CarrierWave::MimeTypes
/Users/jmromer/bikeindex/bike_index/app/uploaders/pdf_uploader.rb:3:in `<class:PdfUploader>'
/Users/jmromer/bikeindex/bike_index/app/uploaders/pdf_uploader.rb:1:in `<top (required)>'
/Users/jmromer/bikeindex/bike_index/app/models/bike.rb:8:in `<class:Bike>'